new_project/routes/web.php
<?php

use App\Http\Controllers\userController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::view('/', 'welcome')->name('home');

Route::resource('/users', 'userController')->names('users');

Route::resource('/plans', 'plansController')->names('plans');

Route::resource('/credits', 'CreditController')->names('credit');

Route::resource('/freeze', 'freezeController')->names('freeze');

new_project/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Plan;
use App\CreditUser;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    /*
    protected $fillable = [
        'name', 'email', 'password',
    ];
    */

    protected $guarded = [];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function plan(){
        return $this->belongsto(Plan::class);
    }

    public function history_plans(){
        return $this->belongsToMany(Plan::class, 'history_plans')->withTimestamps();
    }

    public function credit_user(){
        return $this->hasOne(CreditUser::class);
    }

}

new_project/app/Http/Controllers/userController.php
<?php

namespace App\Http\Controllers;

use App\CreditUser;
use App\HistoryPlan;
use App\User;
use App\Plan;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Requests\SaveUserRequest;
use Illuminate\Support\Facades\Hash;


class userController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $users = User::get();

        $users = User::paginate(5);

        $actual_date = Carbon::now();

        //$users = User::with('plan')->get();
        return view('users.index', [
            'users' => $users,
            'actual_date' => $actual_date
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $plans = Plan::get();
        return view('users.create', compact('plans'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveUserRequest $request)
    {

        // User::create($request->all());

        $user= User::create(array_merge($request->only('name', 'plan_id', 'email'),[
            'password' => Hash::make($request->password)
        ]));
        //dd($user->id);
        //$ultimo_id = User::latest('created_at')->first();

        HistoryPlan::create([
            'user_id' => $user->id,
            'plan_id' => request('plan_id')
        ]);

        CreditUser::create([
            'user_id' => $user->id,
            'total_credits' => $user->plan->credit
        ]);


        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::FindOrfail($id);

        $actual_date = Carbon::now();
        $expired_plan = $user->plan->final_date;

        $final_date = Carbon::parse($expired_plan);

        if($actual_date->gt($final_date)){
            $user->credit_user->update([
                'user_id'=> $user->id,
                'total_credits' => 0
            ]);
        }



        return view('users.show', [
            'user' => $user,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //dd($user);
        $plans = Plan::get();

        return view('users.edit', [
             'user' => $user,
             'plans' => $plans
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(User $user)
    {
        $old_credit = $user->credit_user->total_credits;

        $user->update([
            'name' => request('name'),
            'email' => request('email'),
            'plan_id' => request('plan_id'),
            'password' => Hash::make(request('password'))
        ]);

        HistoryPlan::create([
            'user_id' => $user->id,
            'plan_id' => request('plan_id')
        ]);

        $new_credit = $old_credit + $user->plan->credit;


        $user->credit_user->update([
            'user_id'=> $user->id,
            'total_credits' => $new_credit
        ]);



        return redirect()->route('users.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('users.index');
    }



}

new_project/resources/views/users/create.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-8 mx-auto">

                <form class="bg-white py-3 px-4 shadow rounded"
                    method="POST" action=" {{route('users.store')}} ">

                    @csrf

                    <h1 class="display-4 ">New user</h1>

                    @if ($errors->any())
                        <div class="alert alert-primary">
                            <ul class="m-0">
                                @foreach ($errors->all() as $error)
                                    <li>
                                        {{ $error }}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group">
                        <label>
                            UserName <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                                type="text" name="name">
                    </div>

                    <div class="form-group">
                        <label>
                            Email <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                                type="text" name="email">
                    </div>

                    <div class="form-group">
                        <label>
                            Password <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                                type="password" name="password">
                    </div>

                    <div class="form-group">
                        <select name="plan_id" id="" class="form-control">
                            <option value=""> Choose Plan</option>
                            @foreach ($plans as $plan)

                                <option value=" {{ $plan->id }} "> {{$plan->name}} </option>

                            @endforeach
                        </select>
                    </div>

                    <button class="btn btn-primary btn-lg btn-block">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

new_project/resources/views/users/edit.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="col-12 col-sm-10 col-lg-8 mx-auto">

            <form class="bg-white py-3 px-4 shadow rounded"
                method="POST" action=" {{route('users.update', $user)}} ">
                @csrf @method('PATCH')

                <h1 class="display-4"> User info</h1>

                <div class="form-group">
                <label>
                    UserName
                </label>
                    <input class="form-control border-0 bg-light shadow-sm"
                        type="text" name="name" value="{{ $user->name }}">
                </div>

                <div class="form-group">
                <label>
                    Email
                </label>
                    <input class="form-control border-0 bg-light shadow-sm"
                        type="text" name="email" value=" {{ $user->email}} ">
                </div>

                <div class="form-group">
                <label>
                    Password
                </label>
                    <input  class="form-control border-0 bg-light shadow-sm"
                        type="password" name="password" value=" {{ $user->password}} ">
                </div>

                <div class="form-group">
                        <select name="plan_id" class="form-control">
                            <option> {{$user->plan->name}} </option>
                            @foreach ($plans as $plan)
                                <option value=" {{ $plan->id }} "> {{ $plan->name }} </option>
                            @endforeach
                        </select>
                </div>

                <button class="btn btn-primary btn-lg btn-block">
                    Update
                </button>
            </form>
        </div>
    </div>

@endsection

new_project/resources/views/users/index.blade.php
@extends('layout')

@section('content')

    <div class="container">

        <span class="float-right">{{ $actual_date->format('d/m/Y') }}</span>
        <br>

        <div class="d-flex justify-content-between align-items-center">
            <h1 class="display-4 mb-0">
                All Users
            </h1>

            <a
                href=" {{ route('users.create') }} ">
                <button class="btn btn-primary">
                    Create a new user
                </button>
            </a>
        </div>

        <hr>

        <div class="table-responsive">
            <table class="table table-primary table-striped table-bordered border-primary table-sm text-center">
                <thead>
                <tr>
                    {{-- <th scope="col">User_id</th> --}}
                    <th scope="col">Name</th>
                    <th scope="col">Associate Plan</th>
                    <th scope="col">Disponible Credits</th>
                    <th scope="col">Final date of plan</th>
                    <th scope="col">See details</th>
                    <th scope="col">Credits</th>
                    <th scope="col">Freeze</th>
                </tr>
                </thead>
                <tbody >
                    @foreach ($users as $user)
                        <tr >
                            {{-- <th scope="row"> {{ $user->id}} </th> --}}
                            <td> {{ $user->name}} </td>
                            <td> {{ $user->plan->name }} </td>
                            <td> {{ $user->credit_user->total_credits . '$' }} </td>
                            <td> {{ $user->plan->final_date->format('d/m/Y')}} </td>
                            <td>
                                @if ($user->freeze_defrost == 0)
                                <a  href="{{ route('users.show', $user)}} ">
                                    <button class=" btn btn-outline-primary text-dark">
                                        See user
                                    </button>
                                </a>
                                @else
                                    <button class=" btn btn-outline-primary text-dark">
                                        Blocked
                                    </button>
                                @endif

                            </td>
                            <td>
                                @if ($user->freeze_defrost == 0)
                                <a  href=" {{ route('credit.show', $user) }} ">
                                    <button class=" btn btn-outline-primary text-dark">
                                        Credit user
                                    </button>
                                </a>
                                @else
                                    <button class=" btn btn-outline-primary text-dark">
                                        Blocked
                                    </button>
                                @endif

                            </td>
                            <td>
                                @if ($user->freeze_defrost == 0)
                                    <a  href=" {{ route('freeze.show', $user) }} ">
                                        <button class=" btn btn-outline-primary text-dark">
                                            freeze plan
                                        </button>
                                    </a>
                                @endif
                                @if ($user->freeze_defrost == 1)
                                    <a  href=" {{ route('freeze.show', $user) }} ">
                                        <button class=" btn btn-outline-primary text-dark">
                                            defrost plan
                                        </button>
                                    </a>
                                @endif

                            </td>
                        </tr>

                    @endforeach

                </tbody>
            </table>
        </div>
        {{$users->links()}}
    </div>




@endsection

new_project/resources/views/users/show.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="bg-white p-5 shadow rounded">
            <div class=" justify-content-between p-2 col-6 float-left">
                <h3 class="display-8">
                    {{ 'Name: ' . $user->name }}
                </h3>
                <p class="text-secondary">
                    {{ 'Email: ' . $user->email}}
                </p>

                <p class="text-secondary-50">
                    {{ 'Plan: ' . $user->plan->name}}
                </p>

                <p class="text-secondary-50">
                    {{ 'Disponible credits: ' . $user->credit_user->total_credits . '$'}}
                </p>

                <p class="text-secondary-50">
                    {{ 'Password: ' . $user->password}}
                </p>
            </div>

                {{-- @foreach ($user->history_plans as $history)
                    {{ $history->name }}
                @endforeach --}}
                <div class="table-responsive col-6 float-right">
                    <table class="table table-primary table-striped table-bordered table-hover table-sm text-center">
                        <div class=" justify-content-between">
                            <thead>
                            <tr>
                                {{-- <th scope="col">User_id</th> --}}
                                <th scope="col">History Plans</th>
                                <th scope="col">Date</th>

                            </tr>
                            </thead>
                            <tbody >
                                @foreach ($user->history_plans as $history)
                                    <tr >
                                        {{-- <th scope="row"> {{ $user->id}} </th> --}}
                                        <td> {{ $history->name}} </td>
                                        <td> {{ $history->created_at->format('d/m/Y')}} </td>

                                    </tr>

                                @endforeach

                            </tbody>
                        </div>
                    </table>

               </div>
            <br>


            <div class="d-flex justify-content-between col-12">
                <a
                    href=" {{ route('users.edit', $user)}} ">
                    <button class="btn btn-primary">
                        Edit
                    </button></a>

                <form method="POST" action=" {{route('users.destroy', $user)}} ">
                    @csrf
                    @method('DELETE')

                    <button class="btn btn-danger">
                        Delete
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection