new_project/routes/web.php
<?php

use App\Http\Controllers\userController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::view('/', 'welcome')->name('home');

Route::resource('/users', 'userController')->names('users');

Route::resource('/plans', 'plansController')->names('plans');

Route::resource('/credits', 'CreditController')->names('credit');

Route::resource('/freeze', 'freezeController')->names('freeze');

new_project/app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{

    protected $guarded = [];

    protected $casts = [
        'final_date' => 'datetime:Y-m-d',
    ];

    //protected $table = 'plans';

    public function users(){
        $this->hasMany(User::class);
    }
    public function history_users(){
        return $this->belongsToMany(User::class, 'history_plans')->withTimestamps();
    }
}

new_project/app/Http/Controllers/plansController.php
<?php

namespace App\Http\Controllers;

use App\Plan;
use Carbon\Carbon;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use App\Http\Requests\SavePlanRequest;

class plansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $actual_date = Carbon::now();

        $plans = Plan::get();


        return view('plans.index', [
            'plans' => $plans,
            'actual_date' => $actual_date
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('plans.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SavePlanRequest $request)
    {


        Plan::create($request->all());

        return redirect()->route('plans.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('plans.show', [
            'plan' => Plan::findOrFail($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Plan $plan)
    {
        return view('plans.edit', [
            'plan' => $plan
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Plan $plan)
    {
        $plan->update([
            'name' => request('name'),
            'description' => request('description'),
            'cost' => request('cost'),
            'final_date' => request('final_date')
        ]);
        return redirect()->route('plans.show', $plan);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Plan $plan)
    {
        $plan->delete();

        return redirect()->route('plans.index');
    }
}

new_project/resources/views/plans/create.blade.php
@extends('layout')

@section('content')
    <div class="container">

        <div class="row">

            <div class="col-12 col-sm-10 col-lg-8 mx-auto">



                <form class="bg-white py-3 px-4 shadow rounded"
                    method="POST" action=" {{ route('plans.store') }} ">

                    @csrf




                    <h1 class="display-4 ">
                        New plan
                    </h1>

                    @if($errors->any())
                        <div class="alert alert-primary">
                            <ul class="m-0">
                                @foreach ($errors->all() as $error)
                                    <li>
                                        {{$error}}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group">
                        <label >
                            Name of the plan <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                            type="text" name="name">

                    </div>

                    <div class="form-group">
                        <label >
                            description of the plan <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                            type="text" name="description">

                    </div>

                    <div class="form-group">
                        <label >
                            Cost of the plan <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                            type="numeric" name="cost">
                    </div>
                    <div class="form-group">
                        <label >
                            Credit of the plan <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                            type="numeric" name="credit">
                    </div>
                    <div class="form-group">
                        <label >
                            Final date of the plan <br>
                        </label>
                            <input class="form-control border-0 bg-light shadow-sm"
                            type="date" name="final_date">
                    </div>

                    <button class="btn btn-primary btn-lg btn-block">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

new_project/resources/views/plans/edit.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="col-12 col-sm-10 col-lg-8 mx-auto">


            <form class="bg-white py-3 px-4 shadow rounded"
                method="POST" action=" {{ route('plans.update', $plan) }} ">
                @csrf @method('PATCH')

                <h1 class="display-4">Edit plan</h1>
                <div class="form-group">
                    <label >
                        Name of the plan
                    </label>
                        <input class="form-control border-0 bg-light shadow-sm"
                            type="text" name="name" value=" {{ $plan->name }} ">

                </div>

                <div class="form-group">
                    <label >
                        description of the plan
                    </label>
                        <input class="form-control border-0 bg-light shadow-sm"
                            type="text" name="description" value=" {{ $plan->description }} ">

                </div>

                <div class="form-group">
                    <label >
                        Cost of the plan
                    </label>
                        <input  class="form-control border-0 bg-light shadow-sm"
                            type="text" name="cost" value=" {{ $plan->cost }} ">

                </div>

                <div class="form-group">
                    <label >
                        Modify final date {{$plan->final_date}}
                    </label>
                        <input  class="form-control border-0 bg-light shadow-sm"
                            type="date" name="final_date" value=" {{ $plan->final_date }} ">

                </div>

                <button class="btn btn-primary btn-lg btn-block">
                    Update
                </button>
            </div>
        </div>
    </form>
@endsection

new_project/resources/views/plans/index.blade.php
@extends('layout')

@section('content')

    <div class="container">

        <span class="float-right">{{ $actual_date->format('d/m/Y') }}</span>
        <br>


        <div class="d-flex justify-content-between align-items-center">
            <h1 class="display-4 mb-0">All Plans</h1>

            <a
                href=" {{ route('plans.create')}} ">
                <button class="btn btn-primary">
                    Create a new plan
                </button>
            </a>
        </div>
        <hr>
        <div class="table-responsive">
            <table class="table table-primary table-striped table-bordered border-primary table-sm text-center">
                <thead>
                <tr>
                    <th scope="col">Plan_id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Credit</th>
                    <th scope="col">Final date of plan</th>
                    <th scope="col">Creation Date</th>
                    <th scope="col">See details</th>
                </tr>
                </thead>
                <tbody >
                    @foreach ($plans as $plan)
                        <tr >
                            <th scope="row"> {{ $plan->id}} </th>
                            <td> {{ $plan->name}} </td>
                            <td> {{ $plan->cost . ' $ ' }} </td>
                            <td> {{ $plan->credit . ' $ ' }} </td>
                            <td> {{ $plan->final_date->format('d/m/Y')}} </td>
                            <td> {{ $plan->created_at->format('d/m/Y')}} </td>
                            <td><a class="" href="{{ route('plans.show', $plan)}} ">
                                <button class=" btn btn-outline-primary text-dark">
                                    See plan
                                </button>
                            </a></td>
                        </tr>

                    @endforeach

                </tbody>
            </table>
        </div>

    </div>

@endsection

new_project/resources/views/plans/show.blade.php
@extends('layout')

@section('content')

    <div class="container">
        <div class="bg-white p-5 shadow rounded">


                <h1 class="display-4"> {{ $plan->name }} </h1>

                <p class="text-secondary">
                    {{ $plan->description }}
                </p>
                <p class="text-secondary-50">
                    {{ $plan->cost. ' $ ' }}
                </p>
                <p class="text-secondary-50">
                    {{ $plan->credit . ' $ '  }}
                </p>
                <p class="text-secondary-50">
                    {{ $plan->created_at  }}
                </p>
                <p class="text-secondary-50">
                    {{ $plan->final_date  }}
                </p>

                <div class="d-flex justify-content-between">
                    <a
                        href=" {{ route('plans.edit', $plan)}} ">
                        <button class="btn btn-primary">
                            Edit
                        </button>
                    </a>
                    <br>
                    <form method="POST" action=" {{route('plans.destroy', $plan)}} ">
                        @csrf
                        @method('DELETE')

                        <button class="btn btn-danger">
                            Remove
                        </button>
                    </form>
                </div>

        </div>
    </div>
@endsection